### ISSUE TITLE
PMA0005: Compiling Creative writing data from CTA in a single format. (MM24)

### ISSUE THREAD

**Issue by 10kalden** [OpenPecha/compile-writing-data#1]
### Description:

- We have creative or structured writing data from CTA, that needs to be compiled into a single format.
- We also need to collect metadata such as letter types, dates, tags etc

### Department:
We are expecting data from these department
- [x] Department of Religion and Culture 
- [ ] Department of Information and International Relations
- [x] Department of Home 
- [x] Department of Education
- [x] Kashag (Executive)

### Implementation:
![Image](https://github.com/user-attachments/assets/a8a1d75a-d47a-43fb-ac49-680e8f502b6e)

### Subtask:

- [ ] Collect all the soft-copy data from CTA.
- [x] Collect all hard copy data.
- [x] OCR the scanned document and clean the output
- [x] Convert the data into txt format if they are in any other format.
- [x] Compile all the txt into a JSON with metadata such as types, dates etc

### Completion Criteria
Create JSON with compiled creative writing data from CTA departments

**Comment by 10kalden** [comment]
img.1 compiled data for cta correspondence letter
![Image](https://github.com/user-attachments/assets/e96fc5fc-df76-4b39-a2e4-33d0ca2464e5)

**Comment by 10kalden** [comment]
img.2 compiled data for cta announcement
![Image](https://github.com/user-attachments/assets/d7f0336d-a4cd-4b52-879b-a875d3805aec)

**Comment by 10kalden** [comment]
-compilation of yigdrel and saldak data from DoH, DoE and DoRC is done.
-The scanned documents are being cleaned right now.
-compilation of reports(laydom) are worked on right now.
